'use client'

import { createContext, useContext, useEffect, useMemo, useState } from 'react'

export type AppLanguage = 'en' | 'zh'

type TranslationKey = string

type LanguageContextValue = {
  language: AppLanguage
  setLanguage: (language: AppLanguage) => void
  t: (key: TranslationKey) => string
}

const languageStorageKey = 'dudesign.language'

const translations: Record<AppLanguage, Record<string, string>> = {
  en: {
    addContext: 'Add context',
    addAttachment: 'Add attachment',
    addConnector: 'Connectors',
    addFilesOrPhotos: 'Files or photos',
    addPlugins: 'Plugins',
    advanced: 'Advanced',
    aesthetic: 'Aesthetic',
    automation: 'Automation',
    settings: 'Settings',
    more: 'More',
    profile: 'Profile',
    language: 'Language',
    english: 'English',
    chinese: '中文',
    account: 'Account',
    accountDetail: 'Profile and sign-in settings',
    workspace: 'Workspace',
    workspaceDetail: 'Personal hosted workspace',
    modelPreferences: 'Model preferences',
    modelPreferencesDetail: 'Default model and generation defaults',
    help: 'Help',
    helpDetail: 'Guides and product support',
    feedback: 'Feedback',
    feedbackDetail: 'Send a product note',
    keyboardShortcuts: 'Keyboard shortcuts',
    keyboardShortcutsDetail: 'Reserved for editor shortcuts',
    signOut: 'Sign out',
    signOutDetail: 'Reserved for auth milestone',
    userProfileFor: 'User profile for',
    projectMenu: 'Project menu',
    theme: 'Theme',
    choose: 'Choose',
    connectingWorkspace: 'Connecting workspace...',
    connectors: 'Connectors',
    continueFromUploadedPage: 'Continue from an uploaded page.',
    createFirstDesignSession: 'Create your first design session.',
    designPrompt: 'Design prompt',
    designDirection: 'Design direction',
    productMode: 'Product mode',
    webAppMode: 'Web & App',
    dynamicEncyclopediaMode: 'Dynamic encyclopedia card',
    entryPromptPlaceholder: 'Enter an encyclopedia entry name or content...',
    entryGuidance: 'Entry guidance',
    confidence: 'Confidence',
    democaseReferences: 'Demo cases',
    democaseMatchedKeywords: 'Matched keywords',
    democaseScore: 'Score',
    lowConfidenceGuidance: 'Low confidence. Review the category and recommended template before generating.',
    entryGuidancePending: 'Analyze the entry before generation',
    templateConfirm: 'Template confirmation',
    templateConfirmPending: 'Waiting for recommendations',
    autoReview: 'Auto review',
    semiAutoRepairEnabled: 'Semi-auto repair confirmation enabled',
    autoReviewEnabled: 'Specification review enabled',
    generatePreview: 'Generate preview',
    submittingToRuntime: 'Submitting to runtime',
    generatePreviewPending: 'Ready after confirmation',
    dynamicFlow: 'Dynamic encyclopedia workflow',
    runEntryGuidance: 'Analyze entry guidance',
    domain: 'Domain',
    drafts: 'drafts',
    existingHtml: 'Existing HTML',
    generateFreshStandalonePage: 'Generate a fresh standalone page.',
    generateDesignVariations: 'Generate design variations',
    hostedDesignWorkspace: 'Hosted design workspace',
    designInspiration: 'Design inspiration',
    needInspiration: 'Need inspiration?',
    negativeRequirements: 'Negative requirements',
    loop: 'Automation',
    model: 'Model',
    mcp: 'MCP',
    mvpHosted: 'MVP hosted',
    mySessions: 'My sessions',
    newHtml: 'New HTML',
    noModel: 'No model',
    olderSessionsWillAppear: 'Older sessions will appear here.',
    palette: 'Palette',
    plugins: 'Plugins',
    referenceBrand: 'Reference brand',
    recent: 'Recent',
    earlier: 'Earlier',
    scene: 'Scene',
    search: 'Search',
    searchSessions: 'Search sessions',
    saved: 'saved',
    shared: 'Shared',
    skills: 'Skills',
    sourceMode: 'Source mode',
    startWithYourDesign: '+ Start with your design',
    styles: 'Styles',
    styleNotes: 'Style notes',
    teamWorkspacesReserved: 'Team workspaces are reserved for the collaboration milestone.',
    template: 'Template',
    uploadHtml: 'Upload HTML',
    uploadHtmlToContinue: 'Upload an HTML file to continue from an existing page.',
    uploading: 'Uploading...',
    useLocalHtmlFile: 'Use a local .html file',
    variations: 'Variations',
    visual: 'Visual',
    whatShallWeDesign: 'What shall we design today?',
    startJourney: 'Start your DUdesign journey',
    describePromptPlaceholder: 'Describe the page, product, audience, and tone...',
    workbench: 'DUDesign Workbench',
    newSession: 'New design session',
    notifications: 'Notifications',
    design: 'design',
    // job / runtime
    backToWorkspace: 'Back to workspace',
    jobEyebrow: 'Job',
    variationsCompleted: 'variations completed',
    streaming: 'streaming',
    completed: 'completed',
    running: 'rendering',
    queued: 'queued',
    cancelled: 'cancelled',
    failedLabel: 'failed',
    runtimeActivity: 'Runtime activity',
    variationStatus: 'Variation status',
    activity: 'Activity',
    capabilityActivity: 'Capability activity',
    noCapabilityActivity: 'No capability issues recorded.',
    capability: 'Capability',
    action: 'Action',
    ok: 'OK',
    noActivity: 'No activity yet.',
    copyLatestEvent: 'Copy latest event',
    viewRawStream: 'View raw stream',
    openInEditor: 'Open in editor',
    waitingCodeStream: 'Waiting for code stream…',
    noCodeStream: 'No code stream captured.',
    overall: 'Overall',
    unavailable: 'Unavailable',
    // editor
    allVariations: 'All variations',
    refineThisDesign: 'Refine this design',
    taskTitleLabel: 'Task title',
    loadingVariation: 'Loading variation context…',
    exportHtml: 'Export',
    exporting: 'Exporting',
    shareLink: 'Share',
    sharing: 'Sharing',
    retryImageGeneration: 'Retry image',
    switchProvider: 'Switch provider',
    lockThisVersion: 'Lock this version',
    unlockVersion: 'Unlock',
    unlockedVersion: 'Version unlocked.',
    locked: 'Locked',
    preview: 'Preview',
    code: 'Code',
    desktop: 'Desktop',
    mobile: 'Mobile',
    otherDevices: 'Other',
    drawMode: 'Draw mode',
    on: 'On',
    off: 'Off',
    refinePrompt: 'Refine prompt',
    refinePromptPlaceholder: 'Describe what to change...',
    clear: 'Clear',
    submitRefine: 'Refine',
    refining: 'Refining…',
    tabAnnotate: 'Annotate',
    tabDirection: 'Direction',
    tabInspect: 'Inspect',
    applyMarks: 'Apply marks',
    drawHint: 'Drag on the preview to mark areas',
    drawStageHint: 'Draw on the preview to stage marks.',
    costRuntime: 'Cost & runtime',
    totalCost: 'Total cost',
    tokensLabel: 'Tokens',
    status: 'Status',
    artifactsLabel: 'Artifacts',
    versions: 'Versions',
    currentVersion: 'current',
    restore: 'Restore',
    restoring: 'Restoring',
    currentLocked: 'Current version locked',
    lockedDiffers: 'Locked version differs',
    qualityFailed: 'Quality check failed',
    qualityWarn: 'Quality warning',
    qualityNotice: 'Quality notice',
    latestZip: 'Latest export',
    waitingPreview: 'Waiting for preview',
    // share
    downloadHtml: 'Download HTML',
    copyShareLink: 'Copy share link',
    shareEyebrow: 'Share link',
    loadingShared: 'Loading shared preview…',
    shareAvailable: 'Share link is available · public read-only · preview loaded',
    shareLoadError: 'Preview frame could not load one or more shared resources.',
    shareLoading: 'Loading shared artifact assets…',
    statVariation: 'Variation',
    statVersion: 'Version',
    statSize: 'Size',
    statDevice: 'Device',
    generatedBy: 'Generated by DUDesign · BabeL-O runtime',
    sharedVariation: 'Shared variation',
    downloaded: 'Downloaded',
    shareLinkCreated: 'Share link created.',
    restoredBefore: 'Restored v',
    restoredAfter: ' as the current artifact.',
    lockedBefore: 'Locked v',
    lockedAfter: ' as the selected direction for this variation.',
    readonlyArtifact: 'Read-only artifact',
    sharedUnavailable: 'Shared preview unavailable.',
    sharedPreviewTitle: 'Shared preview',
    exportReservedTitle: 'Exporting from shared links is reserved for a later release.',
    templateLibrary: 'Template library',
    pluginsPill: 'Plugins',
    flowPill: 'Automation',
    pluginTypeSkill: 'Skill',
    pluginTypeMcp: 'MCP tool',
    pluginTypeMixed: 'Skill + MCP',
    contextReserved: 'Reserved for a later release',
    designSystem: 'Design system',
    visualSystem: 'Visual system',
    applyTemplatePack: 'Template pack',
    customDirection: 'Custom',
    packModeHint: 'Apply a complete design system (colors, type, components) from a template pack.',
    customModeHint: 'Compose the visual from an aesthetic profile and palette.',
    officialTemplates: 'Official',
    myTemplates: 'Mine',
    recentTemplates: 'Recent',
    favoriteTemplates: 'Favorites',
    templatesCount: 'templates',
    autoDistribute: 'Auto-assign templates',
    autoDistributeHint: 'With multiple templates selected, assign one per variation automatically.',
    autoDistributeFewHint: 'Fewer templates than variations — some variations will share a template.',
    importDesignMd: 'Import DESIGN.md',
    pasteDesignMd: 'Paste DESIGN.md content',
    designMdName: 'Template name (optional)',
    importing: 'Importing…',
    importSuccess: 'Template imported.',
    importFailed: 'Import failed.',
    saveAsTemplate: 'Save template',
    savedAsTemplate: 'Saved as template.',
    saveAsTemplateFailed: 'Could not save as template.',
    applicableScenarios: 'Best for',
    fontSummary: 'Type',
    dos: 'Do',
    donts: 'Don\'t',
    safetyLevel: 'Safety',
    safe: 'Safe',
    reviewRequired: 'Review required',
    negativeRules: 'Negative constraints',
    ruleSummary: 'Rules',
    qualityChecklist: 'Quality checks',
    myPreferences: 'My preferences',
    defaultTemplate: 'Default template',
    defaultSkill: 'Default skill',
    defaultLoop: 'Default loop',
    advancedConstraints: 'Advanced constraints',
    savePreferences: 'Save preferences',
    preferencesSaved: 'Preferences saved.',
    skillsPill: 'Skills',
    selectSkills: 'Select skills',
    skillsSafeOnlyHint: 'Showing official safe skills only.',
    noPreviewArtifact: 'Preview generated from design tokens',
    previewAttached: 'Preview artifact attached',
    emptyTemplates: 'No templates yet.',
    emptyFavorites: 'No favorites yet.',
    emptyRecent: 'No recently used templates.',
  },
  zh: {
    addContext: '添加上下文',
    addAttachment: '添加附件',
    addConnector: '连接器',
    addFilesOrPhotos: '文件或图片',
    addPlugins: '插件',
    advanced: '进阶',
    aesthetic: '视觉风格',
    automation: '自动化',
    settings: '设置',
    more: '更多',
    profile: '我的',
    language: '语言',
    english: 'English',
    chinese: '中文',
    account: '账号',
    accountDetail: '管理个人信息与登录方式',
    workspace: '工作区',
    workspaceDetail: '个人托管工作区',
    modelPreferences: '模型与生成偏好',
    modelPreferencesDetail: '默认模型与生成参数',
    help: '帮助',
    helpDetail: '查看使用指南与获取支持',
    feedback: '意见反馈',
    feedbackDetail: '告诉我们哪里可以改进',
    keyboardShortcuts: '快捷键',
    keyboardShortcutsDetail: '编辑器快捷键即将开放',
    signOut: '退出登录',
    signOutDetail: '登录功能上线后可用',
    userProfileFor: '用户资料',
    projectMenu: '项目菜单',
    theme: '主题',
    choose: '选择',
    connectingWorkspace: '正在连接工作区…',
    connectors: '连接器',
    continueFromUploadedPage: '在已上传页面的基础上继续。',
    createFirstDesignSession: '从你的第一个设计会话开始。',
    designPrompt: '设计描述',
    designDirection: '设计方向',
    productMode: '产品模式',
    webAppMode: 'Web & App',
    dynamicEncyclopediaMode: '动态百科卡片',
    entryPromptPlaceholder: '输入词条名称或词条内容…',
    entryGuidance: '词条引导',
    confidence: '置信度',
    democaseReferences: '参考案例',
    democaseMatchedKeywords: '命中关键词',
    democaseScore: '命中分',
    lowConfidenceGuidance: '分类置信度较低，请确认分类和推荐模板后再生成。',
    entryGuidancePending: '先分析词条分类与案例',
    templateConfirm: '模板确认',
    templateConfirmPending: '等待推荐模板',
    autoReview: '自动审查',
    semiAutoRepairEnabled: '半自动修复确认已开启',
    autoReviewEnabled: '规范审查已开启',
    generatePreview: '生成预览',
    submittingToRuntime: '正在提交运行时',
    generatePreviewPending: '确认后即可生成',
    dynamicFlow: '动态百科工作流',
    runEntryGuidance: '分析词条引导',
    domain: '场景',
    drafts: '份草稿',
    existingHtml: '基于现有 HTML',
    generateFreshStandalonePage: '生成一个全新的独立页面。',
    generateDesignVariations: '生成设计变体',
    hostedDesignWorkspace: '托管设计工作区',
    designInspiration: '设计灵感',
    needInspiration: '需要灵感?',
    negativeRequirements: '不要出现',
    loop: '自动化',
    model: '模型',
    mcp: 'MCP',
    mvpHosted: 'MVP 托管',
    mySessions: '我的会话',
    newHtml: '全新 HTML',
    noModel: '暂无模型',
    olderSessionsWillAppear: '更早的会话会显示在这里。',
    palette: '色板',
    plugins: '插件',
    referenceBrand: '参考品牌',
    recent: '最近',
    earlier: '更早',
    scene: '场景',
    search: '搜索',
    searchSessions: '搜索会话',
    saved: '个已保存',
    shared: '已共享',
    skills: '技能',
    sourceMode: '生成方式',
    startWithYourDesign: '从你的设计开始 ↗',
    styles: '风格',
    styleNotes: '风格关键词',
    teamWorkspacesReserved: '团队工作区将在协作功能上线后开放。',
    template: '模板',
    uploadHtml: '上传 HTML',
    uploadHtmlToContinue: '上传一个 HTML 文件,基于已有页面继续。',
    uploading: '上传中…',
    useLocalHtmlFile: '使用本地 .html 文件',
    variations: '变体',
    visual: '视觉',
    whatShallWeDesign: '今天我们设计点什么?',
    startJourney: '开启 DUdesign 设计之旅',
    describePromptPlaceholder: '描述你想要的页面:行业、用途、风格、关键模块…',
    workbench: 'DUDesign 工作台',
    newSession: '新建设计会话',
    notifications: '通知',
    design: '设计',
    // job / runtime
    backToWorkspace: '返回工作台',
    jobEyebrow: '任务',
    variationsCompleted: '个变体已完成',
    streaming: '生成中',
    completed: '已完成',
    running: '渲染中',
    queued: '等待中',
    cancelled: '已取消',
    failedLabel: '失败',
    runtimeActivity: '运行时活动',
    variationStatus: '变体状态',
    activity: '动态',
    capabilityActivity: '能力活动',
    noCapabilityActivity: '暂无能力异常记录。',
    capability: '能力',
    action: '动作',
    ok: '正常',
    noActivity: '暂无动态',
    copyLatestEvent: '复制最近事件',
    viewRawStream: '查看原始流',
    openInEditor: '在编辑器中打开',
    waitingCodeStream: '等待代码流…',
    noCodeStream: '暂无代码流',
    overall: '总览',
    unavailable: '不可用',
    // editor
    allVariations: '全部变体',
    refineThisDesign: '精炼此设计',
    taskTitleLabel: '任务标题',
    loadingVariation: '正在加载变体…',
    exportHtml: '导出',
    exporting: '导出中',
    shareLink: '分享',
    sharing: '创建中',
    retryImageGeneration: '重试图片',
    switchProvider: '切换 provider',
    lockThisVersion: '锁定当前版本',
    unlockVersion: '取消锁定',
    unlockedVersion: '已取消锁定。',
    locked: '已锁定',
    preview: '预览',
    code: '代码',
    desktop: '桌面端',
    mobile: '移动端',
    otherDevices: '其他尺寸',
    drawMode: '绘制模式',
    on: '开',
    off: '关',
    refinePrompt: '优化描述',
    refinePromptPlaceholder: '描述你想调整的地方…',
    clear: '清空',
    submitRefine: '继续优化',
    refining: '优化中…',
    tabAnnotate: '标注',
    tabDirection: '方向',
    tabInspect: '检查',
    applyMarks: '应用标注',
    drawHint: '在预览上拖拽即可标注',
    drawStageHint: '在预览上绘制即可暂存标注。',
    costRuntime: '成本与运行时',
    totalCost: '总成本',
    tokensLabel: 'Token 用量',
    status: '状态',
    artifactsLabel: '产物',
    versions: '历史版本',
    currentVersion: '当前',
    restore: '回滚',
    restoring: '回滚中',
    currentLocked: '当前版本已锁定',
    lockedDiffers: '锁定版本与当前不一致',
    qualityFailed: '质量检查未通过',
    qualityWarn: '质量提醒',
    qualityNotice: '质量提示',
    latestZip: '最新导出',
    waitingPreview: '等待预览生成',
    // share
    downloadHtml: '下载 HTML',
    copyShareLink: '复制分享链接',
    shareEyebrow: '分享链接',
    loadingShared: '正在加载分享内容…',
    shareAvailable: '分享链接可用 · 公开只读 · 预览已加载',
    shareLoadError: '预览无法加载部分分享资源。',
    shareLoading: '正在加载分享的资源…',
    statVariation: '变体',
    statVersion: '版本',
    statSize: '大小',
    statDevice: '设备',
    generatedBy: '由 DUDesign 生成 · BabeL-O 运行时',
    sharedVariation: '分享的设计',
    downloaded: '已下载',
    shareLinkCreated: '分享链接已创建。',
    restoredBefore: '已将 v',
    restoredAfter: ' 恢复为当前版本。',
    lockedBefore: '已将 v',
    lockedAfter: ' 锁定为该变体的首选版本。',
    readonlyArtifact: '只读产物',
    sharedUnavailable: '分享预览不可用。',
    sharedPreviewTitle: '分享的预览',
    exportReservedTitle: '分享页的导出将在后续版本开放。',
    templateLibrary: '模板库',
    pluginsPill: '插件',
    flowPill: '自动化',
    pluginTypeSkill: '技能',
    pluginTypeMcp: 'MCP 工具',
    pluginTypeMixed: '技能 + MCP',
    contextReserved: '预留,后续版本开放',
    designSystem: '设计系统',
    visualSystem: '视觉系统',
    applyTemplatePack: '套用模板包',
    customDirection: '自定义方向',
    packModeHint: '套用模板包的完整设计系统(色彩、字体、组件)。',
    customModeHint: '由审美基调与配色自定义视觉系统。',
    officialTemplates: '官方',
    myTemplates: '我的',
    recentTemplates: '最近使用',
    favoriteTemplates: '收藏',
    templatesCount: '个模板',
    autoDistribute: '自动分配模板',
    autoDistributeHint: '选多个模板时,按变体自动分配。',
    autoDistributeFewHint: '模板数少于变体数 —— 部分变体会复用同一模板。',
    importDesignMd: '导入 DESIGN.md',
    pasteDesignMd: '粘贴 DESIGN.md 内容',
    designMdName: '模板名称(可选)',
    importing: '导入中…',
    importSuccess: '模板已导入。',
    importFailed: '导入失败。',
    saveAsTemplate: '保存模版',
    savedAsTemplate: '已保存为模板。',
    saveAsTemplateFailed: '保存模板失败。',
    applicableScenarios: '适用场景',
    fontSummary: '字体',
    dos: '建议',
    donts: '避免',
    safetyLevel: '安全等级',
    safe: '安全',
    reviewRequired: '需审核',
    negativeRules: '负向约束',
    ruleSummary: '规则摘要',
    qualityChecklist: '质量检查',
    myPreferences: '我的偏好',
    defaultTemplate: '默认模板',
    defaultSkill: '默认技能',
    defaultLoop: '默认流程',
    advancedConstraints: '高级约束',
    savePreferences: '保存偏好',
    preferencesSaved: '偏好已保存。',
    skillsPill: '技能',
    selectSkills: '选择技能',
    skillsSafeOnlyHint: '仅展示官方安全技能。',
    noPreviewArtifact: '基于设计令牌生成的预览',
    previewAttached: '已附预览产物',
    emptyTemplates: '暂无模板。',
    emptyFavorites: '暂无收藏。',
    emptyRecent: '暂无最近使用。',
  },
}

const LanguageContext = createContext<LanguageContextValue | null>(null)

export function LanguageProvider(props: { children: React.ReactNode }): React.JSX.Element {
  const [language, setLanguageState] = useState<AppLanguage>('en')
  const [hasLoadedStoredLanguage, setHasLoadedStoredLanguage] = useState(false)

  useEffect(() => {
    try {
      const storedLanguage = window.localStorage.getItem(languageStorageKey)
      if (storedLanguage === 'en' || storedLanguage === 'zh') {
        setLanguageState(storedLanguage)
      }
    } catch {
      // ignore
    }
    setHasLoadedStoredLanguage(true)
  }, [])

  useEffect(() => {
    if (!hasLoadedStoredLanguage) return
    document.documentElement.lang = language === 'zh' ? 'zh-CN' : 'en'
    try {
      window.localStorage.setItem(languageStorageKey, language)
    } catch {
      // ignore
    }
  }, [hasLoadedStoredLanguage, language])

  const value = useMemo<LanguageContextValue>(() => ({
    language,
    setLanguage: setLanguageState,
    t: key => translations[language][key] ?? translations.en[key] ?? key,
  }), [language])

  return <LanguageContext.Provider value={value}>{props.children}</LanguageContext.Provider>
}

export function useLanguage(): LanguageContextValue {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error('useLanguage must be used inside LanguageProvider')
  }
  return context
}
