'use client'

import { createContext, useContext, useEffect, useMemo, useState } from 'react'

export type AppLanguage = 'en' | 'zh'

type TranslationKey = string

type LanguageContextValue = {
  language: AppLanguage
  setLanguage: (language: AppLanguage) => void
  t: (key: TranslationKey) => string
}

const languageStorageKey = 'dudesign.language'

const translations: Record<AppLanguage, Record<string, string>> = {
  en: {
    addContext: 'Add context',
    addAttachment: 'Add attachment',
    addConnector: 'Connectors',
    addFilesOrPhotos: 'Files or photos',
    addPlugins: 'Plugins',
    advanced: 'Advanced',
    aesthetic: 'Aesthetic',
    automation: 'Automation',
    settings: 'Settings',
    more: 'More',
    profile: 'Profile',
    language: 'Language',
    english: 'English',
    chinese: '中文',
    account: 'Account',
    accountDetail: 'Profile and sign-in settings',
    workspace: 'Workspace',
    workspaceDetail: 'Personal hosted workspace',
    modelPreferences: 'Model preferences',
    modelPreferencesDetail: 'Default model and generation defaults',
    help: 'Help',
    helpDetail: 'Guides and product support',
    feedback: 'Feedback',
    feedbackDetail: 'Send a product note',
    keyboardShortcuts: 'Keyboard shortcuts',
    keyboardShortcutsDetail: 'Reserved for editor shortcuts',
    signOut: 'Sign out',
    signOutDetail: 'Reserved for auth milestone',
    userProfileFor: 'User profile for',
    choose: 'Choose',
    connectingWorkspace: 'Connecting workspace...',
    connectors: 'Connectors',
    continueFromUploadedPage: 'Continue from an uploaded page.',
    createFirstDesignSession: 'Create your first design session.',
    designPrompt: 'Design prompt',
    designDirection: 'Design direction',
    domain: 'Domain',
    drafts: 'drafts',
    existingHtml: 'Existing HTML',
    generateFreshStandalonePage: 'Generate a fresh standalone page.',
    generateDesignVariations: 'Generate design variations',
    hostedDesignWorkspace: 'Hosted design workspace',
    designInspiration: 'Design inspiration',
    needInspiration: 'Need inspiration?',
    negativeRequirements: 'Negative requirements',
    loop: 'Loop',
    model: 'Model',
    mcp: 'MCP',
    mvpHosted: 'MVP hosted',
    mySessions: 'My sessions',
    newHtml: 'New HTML',
    noModel: 'No model',
    olderSessionsWillAppear: 'Older sessions will appear here.',
    palette: 'Palette',
    plugins: 'Plugins',
    referenceBrand: 'Reference brand',
    recent: 'Recent',
    earlier: 'Earlier',
    scene: 'Scene',
    search: 'Search',
    searchSessions: 'Search sessions',
    saved: 'saved',
    shared: 'Shared',
    skills: 'Skills',
    sourceMode: 'Source mode',
    startWithYourDesign: '+ Start with your design',
    styles: 'Styles',
    styleNotes: 'Style notes',
    teamWorkspacesReserved: 'Team workspaces are reserved for the collaboration milestone.',
    template: 'Template',
    uploadHtml: 'Upload HTML',
    uploadHtmlToContinue: 'Upload an HTML file to continue from an existing page.',
    uploading: 'Uploading...',
    useLocalHtmlFile: 'Use a local .html file',
    variations: 'Variations',
    visual: 'Visual',
    whatShallWeDesign: 'What shall we design today?',
    describePromptPlaceholder: 'Describe the page, product, audience, and tone...',
    workbench: 'DUDesign Workbench',
    newSession: 'New design session',
    notifications: 'Notifications',
    design: 'design',
    // job / runtime
    backToWorkspace: 'Back to workspace',
    jobEyebrow: 'Job',
    variationsCompleted: 'variations completed',
    streaming: 'streaming',
    completed: 'completed',
    running: 'rendering',
    failedLabel: 'failed',
    runtimeActivity: 'Runtime activity',
    variationStatus: 'Variation status',
    activity: 'Activity',
    noActivity: 'No activity yet.',
    copyLatestEvent: 'Copy latest event',
    viewRawStream: 'View raw stream',
    openInEditor: 'Open in editor',
    waitingCodeStream: 'Waiting for code stream…',
    noCodeStream: 'No code stream captured.',
    overall: 'Overall',
    unavailable: 'Unavailable',
    // editor
    allVariations: 'All variations',
    refineThisDesign: 'Refine this design',
    loadingVariation: 'Loading variation context…',
    exportHtml: 'Export HTML',
    exporting: 'Exporting',
    shareLink: 'Share link',
    sharing: 'Sharing',
    lockThisVersion: 'Lock this version',
    locked: 'Locked',
    preview: 'Preview',
    code: 'Code',
    desktop: 'Desktop',
    mobile: 'Mobile',
    otherDevices: 'Other',
    drawMode: 'Draw mode',
    on: 'On',
    off: 'Off',
    refinePrompt: 'Refine prompt',
    clear: 'Clear',
    submitRefine: 'Refine',
    refining: 'Refining…',
    tabAnnotate: 'Annotate',
    tabDirection: 'Direction',
    tabInspect: 'Inspect',
    applyMarks: 'Apply marks',
    drawHint: 'Drag on the preview to mark areas',
    drawStageHint: 'Draw on the preview to stage marks.',
    costRuntime: 'Cost & runtime',
    totalCost: 'Total cost',
    tokensLabel: 'Tokens',
    status: 'Status',
    artifactsLabel: 'Artifacts',
    versions: 'Versions',
    currentVersion: 'current',
    restore: 'Restore',
    restoring: 'Restoring',
    currentLocked: 'Current version locked',
    lockedDiffers: 'Locked version differs',
    qualityFailed: 'Quality check failed',
    qualityWarn: 'Quality warning',
    latestZip: 'Latest export',
    waitingPreview: 'Waiting for preview',
    // share
    downloadHtml: 'Download HTML',
    copyShareLink: 'Copy share link',
    shareEyebrow: 'Share link',
    loadingShared: 'Loading shared preview…',
    shareAvailable: 'Share link is available · public read-only · preview loaded',
    shareLoadError: 'Preview frame could not load one or more shared resources.',
    shareLoading: 'Loading shared artifact assets…',
    statVariation: 'Variation',
    statVersion: 'Version',
    statSize: 'Size',
    statDevice: 'Device',
    generatedBy: 'Generated by DUDesign · BabeL-O runtime',
    sharedVariation: 'Shared variation',
    downloaded: 'Downloaded',
    shareLinkCreated: 'Share link created.',
    restoredBefore: 'Restored v',
    restoredAfter: ' as the current artifact.',
    lockedBefore: 'Locked v',
    lockedAfter: ' as the selected direction for this variation.',
    readonlyArtifact: 'Read-only artifact',
    sharedUnavailable: 'Shared preview unavailable.',
    sharedPreviewTitle: 'Shared preview',
    exportReservedTitle: 'Exporting from shared links is reserved for a later release.',
  },
  zh: {
    addContext: '添加上下文',
    addAttachment: '添加附件',
    addConnector: '连接器',
    addFilesOrPhotos: '文件或图片',
    addPlugins: '插件',
    advanced: '进阶',
    aesthetic: '视觉风格',
    automation: '自动化',
    settings: '设置',
    more: '更多',
    profile: '我的',
    language: '语言',
    english: 'English',
    chinese: '中文',
    account: '账号',
    accountDetail: '管理个人信息与登录方式',
    workspace: '工作区',
    workspaceDetail: '个人托管工作区',
    modelPreferences: '模型与生成偏好',
    modelPreferencesDetail: '默认模型与生成参数',
    help: '帮助',
    helpDetail: '查看使用指南与获取支持',
    feedback: '意见反馈',
    feedbackDetail: '告诉我们哪里可以改进',
    keyboardShortcuts: '快捷键',
    keyboardShortcutsDetail: '编辑器快捷键即将开放',
    signOut: '退出登录',
    signOutDetail: '登录功能上线后可用',
    userProfileFor: '用户资料',
    choose: '选择',
    connectingWorkspace: '正在连接工作区…',
    connectors: '连接器',
    continueFromUploadedPage: '在已上传页面的基础上继续。',
    createFirstDesignSession: '从你的第一个设计会话开始。',
    designPrompt: '设计描述',
    designDirection: '设计方向',
    domain: '场景',
    drafts: '份草稿',
    existingHtml: '基于现有 HTML',
    generateFreshStandalonePage: '生成一个全新的独立页面。',
    generateDesignVariations: '生成设计变体',
    hostedDesignWorkspace: '托管设计工作区',
    designInspiration: '设计灵感',
    needInspiration: '需要灵感?',
    negativeRequirements: '不要出现',
    loop: '流程',
    model: '模型',
    mcp: 'MCP',
    mvpHosted: 'MVP 托管',
    mySessions: '我的会话',
    newHtml: '全新 HTML',
    noModel: '暂无模型',
    olderSessionsWillAppear: '更早的会话会显示在这里。',
    palette: '色板',
    plugins: '插件',
    referenceBrand: '参考品牌',
    recent: '最近',
    earlier: '更早',
    scene: '场景',
    search: '搜索',
    searchSessions: '搜索会话',
    saved: '个已保存',
    shared: '已共享',
    skills: '技能',
    sourceMode: '生成方式',
    startWithYourDesign: '从你的设计开始 ↗',
    styles: '风格',
    styleNotes: '风格关键词',
    teamWorkspacesReserved: '团队工作区将在协作功能上线后开放。',
    template: '模板',
    uploadHtml: '上传 HTML',
    uploadHtmlToContinue: '上传一个 HTML 文件,基于已有页面继续。',
    uploading: '上传中…',
    useLocalHtmlFile: '使用本地 .html 文件',
    variations: '变体',
    visual: '视觉',
    whatShallWeDesign: '今天我们设计点什么?',
    describePromptPlaceholder: '描述你想要的页面:行业、用途、风格、关键模块…',
    workbench: 'DUDesign 工作台',
    newSession: '新建设计会话',
    notifications: '通知',
    design: '设计',
    // job / runtime
    backToWorkspace: '返回工作台',
    jobEyebrow: '任务',
    variationsCompleted: '个变体已完成',
    streaming: '生成中',
    completed: '已完成',
    running: '渲染中',
    failedLabel: '失败',
    runtimeActivity: '运行时活动',
    variationStatus: '变体状态',
    activity: '动态',
    noActivity: '暂无动态',
    copyLatestEvent: '复制最近事件',
    viewRawStream: '查看原始流',
    openInEditor: '在编辑器中打开',
    waitingCodeStream: '等待代码流…',
    noCodeStream: '暂无代码流',
    overall: '总览',
    unavailable: '不可用',
    // editor
    allVariations: '全部变体',
    refineThisDesign: '精炼此设计',
    loadingVariation: '正在加载变体…',
    exportHtml: '导出 HTML',
    exporting: '导出中',
    shareLink: '创建分享链接',
    sharing: '创建中',
    lockThisVersion: '锁定当前版本',
    locked: '已锁定',
    preview: '预览',
    code: '代码',
    desktop: '桌面端',
    mobile: '移动端',
    otherDevices: '其他尺寸',
    drawMode: '绘制模式',
    on: '开',
    off: '关',
    refinePrompt: '优化描述',
    clear: '清空',
    submitRefine: '继续优化',
    refining: '优化中…',
    tabAnnotate: '标注',
    tabDirection: '方向',
    tabInspect: '检查',
    applyMarks: '应用标注',
    drawHint: '在预览上拖拽即可标注',
    drawStageHint: '在预览上绘制即可暂存标注。',
    costRuntime: '成本与运行时',
    totalCost: '总成本',
    tokensLabel: 'Token 用量',
    status: '状态',
    artifactsLabel: '产物',
    versions: '历史版本',
    currentVersion: '当前',
    restore: '回滚',
    restoring: '回滚中',
    currentLocked: '当前版本已锁定',
    lockedDiffers: '锁定版本与当前不一致',
    qualityFailed: '质量检查未通过',
    qualityWarn: '质量提醒',
    latestZip: '最新导出',
    waitingPreview: '等待预览生成',
    // share
    downloadHtml: '下载 HTML',
    copyShareLink: '复制分享链接',
    shareEyebrow: '分享链接',
    loadingShared: '正在加载分享内容…',
    shareAvailable: '分享链接可用 · 公开只读 · 预览已加载',
    shareLoadError: '预览无法加载部分分享资源。',
    shareLoading: '正在加载分享的资源…',
    statVariation: '变体',
    statVersion: '版本',
    statSize: '大小',
    statDevice: '设备',
    generatedBy: '由 DUDesign 生成 · BabeL-O 运行时',
    sharedVariation: '分享的设计',
    downloaded: '已下载',
    shareLinkCreated: '分享链接已创建。',
    restoredBefore: '已将 v',
    restoredAfter: ' 恢复为当前版本。',
    lockedBefore: '已将 v',
    lockedAfter: ' 锁定为该变体的首选版本。',
    readonlyArtifact: '只读产物',
    sharedUnavailable: '分享预览不可用。',
    sharedPreviewTitle: '分享的预览',
    exportReservedTitle: '分享页的导出将在后续版本开放。',
  },
}

const LanguageContext = createContext<LanguageContextValue | null>(null)

export function LanguageProvider(props: { children: React.ReactNode }): React.JSX.Element {
  const [language, setLanguageState] = useState<AppLanguage>('en')
  const [hasLoadedStoredLanguage, setHasLoadedStoredLanguage] = useState(false)

  useEffect(() => {
    try {
      const storedLanguage = window.localStorage.getItem(languageStorageKey)
      if (storedLanguage === 'en' || storedLanguage === 'zh') {
        setLanguageState(storedLanguage)
      }
    } catch {
      // ignore
    }
    setHasLoadedStoredLanguage(true)
  }, [])

  useEffect(() => {
    if (!hasLoadedStoredLanguage) return
    document.documentElement.lang = language === 'zh' ? 'zh-CN' : 'en'
    try {
      window.localStorage.setItem(languageStorageKey, language)
    } catch {
      // ignore
    }
  }, [hasLoadedStoredLanguage, language])

  const value = useMemo<LanguageContextValue>(() => ({
    language,
    setLanguage: setLanguageState,
    t: key => translations[language][key] ?? translations.en[key] ?? key,
  }), [language])

  return <LanguageContext.Provider value={value}>{props.children}</LanguageContext.Provider>
}

export function useLanguage(): LanguageContextValue {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error('useLanguage must be used inside LanguageProvider')
  }
  return context
}
