import type { DesignTemplatePack } from '@dudesign/contracts'
import { DESIGN_TEMPLATE_PACK_SCHEMA_VERSION } from './designTemplatePack.js'

export const officialDesignTemplatePacks: DesignTemplatePack[] = [
  {
    schemaVersion: DESIGN_TEMPLATE_PACK_SCHEMA_VERSION,
    id: 'dtp_premium_product_launch',
    source: 'official',
    format: 'dudesign-template-v1',
    visibility: 'public',
    status: 'published',
    name: 'Premium Product Launch',
    description: 'A restrained product launch system for tactile, high-value digital or physical products.',
    version: '1.0.0',
    designTokens: {
      colors: {
        primary: '#171717',
        'on-primary': '#FFFFFF',
        background: '#F7F5F0',
        surface: '#FFFFFF',
        accent: '#6F7D5D',
      },
      typography: {
        display: { fontFamily: 'Inter, ui-sans-serif, system-ui', fontSize: '56px', fontWeight: 650, lineHeight: 1.02 },
        body: { fontFamily: 'Inter, ui-sans-serif, system-ui', fontSize: '16px', fontWeight: 400, lineHeight: 1.6 },
      },
      spacing: { xs: '6px', sm: '12px', md: '24px', lg: '48px', xl: '80px' },
      rounded: { sm: '6px', md: '10px', lg: '18px' },
      components: {
        'button-primary': { backgroundColor: '{colors.primary}', textColor: '{colors.on-primary}', rounded: '{rounded.sm}' },
        'product-panel': { backgroundColor: '{colors.surface}', rounded: '{rounded.lg}' },
      },
    },
    rationale: {
      overview: 'Use calm premium hierarchy, strong product focus, and spacious comparison moments.',
      colors: 'Warm neutral surfaces carry most of the page; accent color is used sparingly for proof or progress states.',
      typography: 'Large compact headlines paired with quiet body copy. Avoid decorative type.',
      layout: 'Hero first, proof second, product detail third. Keep product imagery or generated product mockups inspectable.',
      elevation: 'Use shallow elevation only for product panels and sticky actions.',
      shapes: 'Prefer restrained radii and simple silhouettes.',
      components: 'Primary buttons are direct and dark; cards are used only for repeated product details or comparisons.',
      dos: ['Show the actual product or interface early.', 'Use one decisive CTA per viewport.'],
      donts: ['Do not copy any public brand chrome, product photography style, logos, or proprietary copy.', 'Do not turn the page into a generic gradient hero.'],
      sections: {},
    },
    previewArtifactId: null,
    lintStatus: 'unknown',
    createdByUserId: null,
  },
  {
    schemaVersion: DESIGN_TEMPLATE_PACK_SCHEMA_VERSION,
    id: 'dtp_trust_fintech',
    source: 'official',
    format: 'dudesign-template-v1',
    visibility: 'public',
    status: 'published',
    name: 'Trust-Centered Fintech',
    description: 'A clear, compliance-aware financial product system for trust, comparison, and conversion.',
    version: '1.0.0',
    designTokens: {
      colors: {
        primary: '#123C3A',
        'on-primary': '#FFFFFF',
        background: '#F4F7F5',
        surface: '#FFFFFF',
        accent: '#3B82F6',
        warning: '#B45309',
      },
      typography: {
        display: { fontFamily: 'Inter, ui-sans-serif, system-ui', fontSize: '48px', fontWeight: 680, lineHeight: 1.08 },
        body: { fontFamily: 'Inter, ui-sans-serif, system-ui', fontSize: '16px', fontWeight: 400, lineHeight: 1.58 },
      },
      spacing: { sm: '10px', md: '20px', lg: '40px', xl: '72px' },
      rounded: { sm: '4px', md: '8px', lg: '14px' },
      components: {
        'metric-card': { backgroundColor: '{colors.surface}', rounded: '{rounded.md}' },
        'button-primary': { backgroundColor: '{colors.primary}', textColor: '{colors.on-primary}', rounded: '{rounded.sm}' },
      },
    },
    rationale: {
      overview: 'Prioritize legibility, proof, pricing clarity, and explicit risk or security language.',
      colors: 'Stable greens and whites should dominate; bright blue is reserved for links and verified actions.',
      typography: 'Use plain language and numerals that scan quickly.',
      layout: 'Comparison tables, trust bands, and calculator-like modules should be easy to audit.',
      elevation: 'Minimal shadows. Trust comes from structure and content, not gloss.',
      shapes: 'Moderate radius only; avoid playful shapes.',
      components: 'Use metric cards, disclosure rows, fee tables, and security badges with restrained styling.',
      dos: ['Surface fees, limits, and security details plainly.', 'Use realistic financial examples without overpromising outcomes.'],
      donts: ['Do not imitate bank, card network, or payment company trade dress.', 'Do not hide risk language in tiny text.'],
      sections: {},
    },
    previewArtifactId: null,
    lintStatus: 'unknown',
    createdByUserId: null,
  },
  {
    schemaVersion: DESIGN_TEMPLATE_PACK_SCHEMA_VERSION,
    id: 'dtp_editorial_creative_portfolio',
    source: 'official',
    format: 'dudesign-template-v1',
    visibility: 'public',
    status: 'published',
    name: 'Editorial Creative Portfolio',
    description: 'A portfolio system for artists, studios, photographers, and experimental creative work.',
    version: '1.0.0',
    designTokens: {
      colors: {
        primary: '#202020',
        'on-primary': '#FAFAF7',
        background: '#FBFAF6',
        surface: '#FFFFFF',
        accent: '#D86C4A',
      },
      typography: {
        display: { fontFamily: 'Georgia, ui-serif, serif', fontSize: '58px', fontWeight: 500, lineHeight: 1.0 },
        body: { fontFamily: 'Inter, ui-sans-serif, system-ui', fontSize: '16px', fontWeight: 400, lineHeight: 1.7 },
      },
      spacing: { sm: '12px', md: '24px', lg: '56px', xl: '96px' },
      rounded: { sm: '2px', md: '6px', lg: '8px' },
      components: {
        'project-tile': { backgroundColor: '{colors.surface}', rounded: '{rounded.md}' },
        'button-primary': { backgroundColor: '{colors.primary}', textColor: '{colors.on-primary}', rounded: '{rounded.sm}' },
      },
    },
    rationale: {
      overview: 'Give work samples room to breathe and let captions carry the story.',
      colors: 'Mostly monochrome with one editorial accent for active states and tags.',
      typography: 'Pair expressive display type with neutral UI labels.',
      layout: 'Use magazine-like rhythm, alternating scale, and strong image or canvas placements.',
      elevation: 'Flat by default; depth comes from image scale and whitespace.',
      shapes: 'Keep framing quiet so the creative work stays primary.',
      components: 'Project tiles, filters, captions, and contact modules should feel curated rather than dashboard-like.',
      dos: ['Show concrete work above the fold.', 'Make project metadata scannable.'],
      donts: ['Do not copy a known magazine, gallery, studio, or portfolio trade dress.', 'Do not use stock-like abstract backgrounds as the main proof.', 'Do not overcrowd the page with badges.'],
      sections: {},
    },
    previewArtifactId: null,
    lintStatus: 'unknown',
    createdByUserId: null,
  },
  {
    schemaVersion: DESIGN_TEMPLATE_PACK_SCHEMA_VERSION,
    id: 'dtp_enterprise_clarity',
    source: 'official',
    format: 'dudesign-template-v1',
    visibility: 'public',
    status: 'published',
    name: 'Enterprise Clarity',
    description: 'A sober B2B system for complex products, procurement confidence, and repeated scanning.',
    version: '1.0.0',
    designTokens: {
      colors: {
        primary: '#253247',
        'on-primary': '#FFFFFF',
        background: '#F6F7F9',
        surface: '#FFFFFF',
        accent: '#2F6FED',
      },
      typography: {
        display: { fontFamily: 'Inter, ui-sans-serif, system-ui', fontSize: '44px', fontWeight: 680, lineHeight: 1.12 },
        body: { fontFamily: 'Inter, ui-sans-serif, system-ui', fontSize: '15px', fontWeight: 400, lineHeight: 1.62 },
      },
      spacing: { sm: '8px', md: '18px', lg: '36px', xl: '64px' },
      rounded: { sm: '4px', md: '8px', lg: '12px' },
      components: {
        'feature-row': { backgroundColor: '{colors.surface}', rounded: '{rounded.md}' },
        'button-primary': { backgroundColor: '{colors.primary}', textColor: '{colors.on-primary}', rounded: '{rounded.sm}' },
      },
    },
    rationale: {
      overview: 'Keep dense information orderly, with trust proof and implementation context close to claims.',
      colors: 'Neutral operational colors with blue reserved for navigation, links, and primary actions.',
      typography: 'Professional and compact. Favor subheads and labels that support scanning.',
      layout: 'Use clear bands, tables, diagrams, and side-by-side evidence blocks.',
      elevation: 'Low depth; use borders and banding for separation.',
      shapes: 'Conservative radius, no playful decorative forms.',
      components: 'Feature matrices, integration lists, role-based use cases, and security sections are first-class.',
      dos: ['Make deployment and security concerns visible.', 'Support comparison and repeated review.'],
      donts: ['Do not copy or imitate a specific enterprise software homepage or console trade dress.', 'Do not use oversized marketing-only hero composition for operational tools.', 'Do not obscure dense data inside decorative cards.'],
      sections: {},
    },
    previewArtifactId: null,
    lintStatus: 'unknown',
    createdByUserId: null,
  },
  {
    schemaVersion: DESIGN_TEMPLATE_PACK_SCHEMA_VERSION,
    id: 'dtp_mobility_launch',
    source: 'official',
    format: 'dudesign-template-v1',
    visibility: 'public',
    status: 'published',
    name: 'Mobility Launch',
    description: 'A motion-aware launch system for automotive, transportation, robotics, and hardware mobility.',
    version: '1.0.0',
    designTokens: {
      colors: {
        primary: '#101113',
        'on-primary': '#FFFFFF',
        background: '#F5F2EC',
        surface: '#FFFFFF',
        accent: '#B91C1C',
      },
      typography: {
        display: { fontFamily: 'Inter, ui-sans-serif, system-ui', fontSize: '54px', fontWeight: 720, lineHeight: 1.0 },
        body: { fontFamily: 'Inter, ui-sans-serif, system-ui', fontSize: '16px', fontWeight: 400, lineHeight: 1.55 },
      },
      spacing: { sm: '10px', md: '22px', lg: '48px', xl: '88px' },
      rounded: { sm: '4px', md: '10px', lg: '20px' },
      components: {
        'spec-strip': { backgroundColor: '{colors.primary}', textColor: '{colors.on-primary}', rounded: '{rounded.md}' },
        'button-primary': { backgroundColor: '{colors.accent}', textColor: '{colors.on-primary}', rounded: '{rounded.sm}' },
      },
    },
    rationale: {
      overview: 'Use strong silhouettes, specs, and motion cues while keeping the object inspectable.',
      colors: 'Charcoal and warm neutrals dominate; red accent adds urgency without becoming a brand clone.',
      typography: 'Confident technical headlines with compact spec labels.',
      layout: 'Lead with the vehicle or hardware object, then show specs, experience, safety, and availability.',
      elevation: 'Use layered panels only where specs need contrast.',
      shapes: 'Use subtle aerodynamic curves in layout, not decorative blobs.',
      components: 'Spec strips, model comparison, safety highlights, and configurator-like controls are key.',
      dos: ['Show product form, scale, and practical details.', 'Use motion cues to support understanding.'],
      donts: ['Do not imitate any automaker grille, badge, typography, launch page, or photography trade dress.', 'Do not hide safety information behind vibe-only visuals.'],
      sections: {},
    },
    previewArtifactId: null,
    lintStatus: 'unknown',
    createdByUserId: null,
  },
  {
    schemaVersion: DESIGN_TEMPLATE_PACK_SCHEMA_VERSION,
    id: 'dtp_developer_workflow',
    source: 'official',
    format: 'dudesign-template-v1',
    visibility: 'public',
    status: 'published',
    name: 'Developer Workflow',
    description: 'A precise developer-tool system for APIs, CLIs, infrastructure, and code-adjacent products.',
    version: '1.0.0',
    designTokens: {
      colors: {
        primary: '#0F172A',
        'on-primary': '#E5E7EB',
        background: '#F8FAFC',
        surface: '#FFFFFF',
        accent: '#14B8A6',
      },
      typography: {
        display: { fontFamily: 'Inter, ui-sans-serif, system-ui', fontSize: '46px', fontWeight: 700, lineHeight: 1.08 },
        mono: { fontFamily: 'JetBrains Mono, ui-monospace, monospace', fontSize: '13px', fontWeight: 500, lineHeight: 1.55 },
        body: { fontFamily: 'Inter, ui-sans-serif, system-ui', fontSize: '16px', fontWeight: 400, lineHeight: 1.6 },
      },
      spacing: { sm: '8px', md: '18px', lg: '40px', xl: '72px' },
      rounded: { sm: '4px', md: '8px', lg: '12px' },
      components: {
        'code-panel': { backgroundColor: '{colors.primary}', textColor: '{colors.on-primary}', rounded: '{rounded.md}' },
        'button-primary': { backgroundColor: '{colors.accent}', textColor: '{colors.primary}', rounded: '{rounded.sm}' },
      },
    },
    rationale: {
      overview: 'Make implementation feel obvious: code samples, workflow steps, and integration state should be first-class.',
      colors: 'Dark code panels contrast with light documentation surfaces; teal accent marks success or active state.',
      typography: 'Use a trustworthy sans for product copy and a readable mono only for real code or commands.',
      layout: 'Expose API examples, quickstart steps, and architecture diagrams without overwhelming the first viewport.',
      elevation: 'Prefer borders and terminal-like panels over heavy shadows.',
      shapes: 'Crisp edges and predictable controls.',
      components: 'Code panels, tabs, copy buttons, status badges, and changelog snippets are expected.',
      dos: ['Include plausible code or CLI examples.', 'Make docs and product value connect in the same flow.'],
      donts: ['Do not fake unreadable code texture.', 'Do not copy any specific developer platform landing page chrome.'],
      sections: {},
    },
    previewArtifactId: null,
    lintStatus: 'unknown',
    createdByUserId: null,
  },
  {
    schemaVersion: DESIGN_TEMPLATE_PACK_SCHEMA_VERSION,
    id: 'dtp_warm_commerce',
    source: 'official',
    format: 'dudesign-template-v1',
    visibility: 'public',
    status: 'published',
    name: 'Warm Commerce',
    description: 'A product-commerce system for curated goods, lifestyle offers, and approachable conversion.',
    version: '1.0.0',
    designTokens: {
      colors: {
        primary: '#312A25',
        'on-primary': '#FFFFFF',
        background: '#FAF6EF',
        surface: '#FFFFFF',
        accent: '#C96A43',
      },
      typography: {
        display: { fontFamily: 'Inter, ui-sans-serif, system-ui', fontSize: '50px', fontWeight: 660, lineHeight: 1.06 },
        body: { fontFamily: 'Inter, ui-sans-serif, system-ui', fontSize: '16px', fontWeight: 400, lineHeight: 1.64 },
      },
      spacing: { sm: '10px', md: '22px', lg: '44px', xl: '76px' },
      rounded: { sm: '6px', md: '12px', lg: '18px' },
      components: {
        'product-card': { backgroundColor: '{colors.surface}', rounded: '{rounded.md}' },
        'button-primary': { backgroundColor: '{colors.primary}', textColor: '{colors.on-primary}', rounded: '{rounded.sm}' },
      },
    },
    rationale: {
      overview: 'Balance warmth, product inspection, and purchasing clarity.',
      colors: 'Soft commerce neutrals with a single warm accent for price, promo, or availability.',
      typography: 'Friendly but not cute; support product detail scanning.',
      layout: 'Product grids, bundles, story bands, and trust proof should remain clean and transactional.',
      elevation: 'Subtle depth on product cards only.',
      shapes: 'Moderate radius for approachability.',
      components: 'Product cards, bundles, review snippets, variant selectors, and sticky buy actions are core.',
      dos: ['Make product details and purchase path visible.', 'Use real product imagery or generated product-like assets when needed.'],
      donts: ['Do not bury buying controls under editorial content.', 'Do not copy any marketplace or fashion brand trade dress.'],
      sections: {},
    },
    previewArtifactId: null,
    lintStatus: 'unknown',
    createdByUserId: null,
  },
  {
    schemaVersion: DESIGN_TEMPLATE_PACK_SCHEMA_VERSION,
    id: 'dtp_data_operations',
    source: 'official',
    format: 'dudesign-template-v1',
    visibility: 'public',
    status: 'published',
    name: 'Data-Dense Operations',
    description: 'A compact operational system for dashboards, admin tools, monitoring, and repeated workflows.',
    version: '1.0.0',
    designTokens: {
      colors: {
        primary: '#1F2937',
        'on-primary': '#FFFFFF',
        background: '#F3F4F6',
        surface: '#FFFFFF',
        accent: '#2563EB',
        success: '#047857',
        danger: '#B91C1C',
      },
      typography: {
        display: { fontFamily: 'Inter, ui-sans-serif, system-ui', fontSize: '34px', fontWeight: 700, lineHeight: 1.14 },
        body: { fontFamily: 'Inter, ui-sans-serif, system-ui', fontSize: '14px', fontWeight: 400, lineHeight: 1.55 },
        label: { fontFamily: 'Inter, ui-sans-serif, system-ui', fontSize: '12px', fontWeight: 650, lineHeight: 1.25 },
      },
      spacing: { xs: '4px', sm: '8px', md: '16px', lg: '28px', xl: '48px' },
      rounded: { sm: '4px', md: '8px', lg: '10px' },
      components: {
        'data-table': { backgroundColor: '{colors.surface}', rounded: '{rounded.md}' },
        'button-primary': { backgroundColor: '{colors.accent}', textColor: '{colors.on-primary}', rounded: '{rounded.sm}' },
      },
    },
    rationale: {
      overview: 'Prioritize scanning, comparison, filters, error states, and fast repeated action.',
      colors: 'Neutral operational surfaces with semantic status colors.',
      typography: 'Dense, legible, and label-driven.',
      layout: 'Navigation, filters, tables, charts, and detail drawers should be predictable and stable.',
      elevation: 'Use borders and layout bands before shadows.',
      shapes: 'Small radii preserve density.',
      components: 'Tables, filters, tabs, segmented controls, drawers, and metric strips are primary.',
      dos: ['Keep workflows dense but organized.', 'Show empty, loading, and error states.'],
      donts: ['Do not copy or imitate a specific analytics, monitoring, or admin platform trade dress.', 'Do not make a marketing landing page for an operational tool.', 'Do not use oversized cards where tables or lists are more useful.'],
      sections: {},
    },
    previewArtifactId: null,
    lintStatus: 'unknown',
    createdByUserId: null,
  },
]
