import type { DesignTemplatePack } from '@dudesign/contracts'
import { DESIGN_TEMPLATE_PACK_SCHEMA_VERSION } from './designTemplatePack.js'

export const officialDesignTemplatePacks: DesignTemplatePack[] = [
  {
    schemaVersion: DESIGN_TEMPLATE_PACK_SCHEMA_VERSION,
    id: 'dtp_premium_product_launch',
    source: 'official',
    format: 'dudesign-template-v1',
    visibility: 'public',
    status: 'published',
    name: 'Premium Product Launch',
    description: 'A restrained product launch system for tactile, high-value digital or physical products.',
    version: '1.0.0',
    designTokens: {
      colors: {
        primary: '#171717',
        'on-primary': '#FFFFFF',
        background: '#F7F5F0',
        surface: '#FFFFFF',
        accent: '#6F7D5D',
      },
      typography: {
        display: { fontFamily: 'Inter, ui-sans-serif, system-ui', fontSize: '56px', fontWeight: 650, lineHeight: 1.02 },
        body: { fontFamily: 'Inter, ui-sans-serif, system-ui', fontSize: '16px', fontWeight: 400, lineHeight: 1.6 },
      },
      spacing: { xs: '6px', sm: '12px', md: '24px', lg: '48px', xl: '80px' },
      rounded: { sm: '6px', md: '10px', lg: '18px' },
      components: {
        'button-primary': { backgroundColor: '{colors.primary}', textColor: '{colors.on-primary}', rounded: '{rounded.sm}' },
        'product-panel': { backgroundColor: '{colors.surface}', rounded: '{rounded.lg}' },
      },
    },
    rationale: {
      overview: 'Use calm premium hierarchy, strong product focus, and spacious comparison moments.',
      colors: 'Warm neutral surfaces carry most of the page; accent color is used sparingly for proof or progress states.',
      typography: 'Large compact headlines paired with quiet body copy. Avoid decorative type.',
      layout: 'Hero first, proof second, product detail third. Keep product imagery or generated product mockups inspectable.',
      elevation: 'Use shallow elevation only for product panels and sticky actions.',
      shapes: 'Prefer restrained radii and simple silhouettes.',
      components: 'Primary buttons are direct and dark; cards are used only for repeated product details or comparisons.',
      dos: ['Show the actual product or interface early.', 'Use one decisive CTA per viewport.'],
      donts: ['Do not copy any public brand chrome, product photography style, logos, or proprietary copy.', 'Do not turn the page into a generic gradient hero.'],
      sections: {},
    },
    previewArtifactId: null,
    lintStatus: 'unknown',
    createdByUserId: null,
  },
  {
    schemaVersion: DESIGN_TEMPLATE_PACK_SCHEMA_VERSION,
    id: 'dtp_trust_fintech',
    source: 'official',
    format: 'dudesign-template-v1',
    visibility: 'public',
    status: 'published',
    name: 'Trust-Centered Fintech',
    description: 'A clear, compliance-aware financial product system for trust, comparison, and conversion.',
    version: '1.0.0',
    designTokens: {
      colors: {
        primary: '#123C3A',
        'on-primary': '#FFFFFF',
        background: '#F4F7F5',
        surface: '#FFFFFF',
        accent: '#3B82F6',
        warning: '#B45309',
      },
      typography: {
        display: { fontFamily: 'Inter, ui-sans-serif, system-ui', fontSize: '48px', fontWeight: 680, lineHeight: 1.08 },
        body: { fontFamily: 'Inter, ui-sans-serif, system-ui', fontSize: '16px', fontWeight: 400, lineHeight: 1.58 },
      },
      spacing: { sm: '10px', md: '20px', lg: '40px', xl: '72px' },
      rounded: { sm: '4px', md: '8px', lg: '14px' },
      components: {
        'metric-card': { backgroundColor: '{colors.surface}', rounded: '{rounded.md}' },
        'button-primary': { backgroundColor: '{colors.primary}', textColor: '{colors.on-primary}', rounded: '{rounded.sm}' },
      },
    },
    rationale: {
      overview: 'Prioritize legibility, proof, pricing clarity, and explicit risk or security language.',
      colors: 'Stable greens and whites should dominate; bright blue is reserved for links and verified actions.',
      typography: 'Use plain language and numerals that scan quickly.',
      layout: 'Comparison tables, trust bands, and calculator-like modules should be easy to audit.',
      elevation: 'Minimal shadows. Trust comes from structure and content, not gloss.',
      shapes: 'Moderate radius only; avoid playful shapes.',
      components: 'Use metric cards, disclosure rows, fee tables, and security badges with restrained styling.',
      dos: ['Surface fees, limits, and security details plainly.', 'Use realistic financial examples without overpromising outcomes.'],
      donts: ['Do not imitate bank, card network, or payment company trade dress.', 'Do not hide risk language in tiny text.'],
      sections: {},
    },
    previewArtifactId: null,
    lintStatus: 'unknown',
    createdByUserId: null,
  },
  {
    schemaVersion: DESIGN_TEMPLATE_PACK_SCHEMA_VERSION,
    id: 'dtp_editorial_creative_portfolio',
    source: 'official',
    format: 'dudesign-template-v1',
    visibility: 'public',
    status: 'published',
    name: 'Editorial Creative Portfolio',
    description: 'A portfolio system for artists, studios, photographers, and experimental creative work.',
    version: '1.0.0',
    designTokens: {
      colors: {
        primary: '#202020',
        'on-primary': '#FAFAF7',
        background: '#FBFAF6',
        surface: '#FFFFFF',
        accent: '#D86C4A',
      },
      typography: {
        display: { fontFamily: 'Georgia, ui-serif, serif', fontSize: '58px', fontWeight: 500, lineHeight: 1.0 },
        body: { fontFamily: 'Inter, ui-sans-serif, system-ui', fontSize: '16px', fontWeight: 400, lineHeight: 1.7 },
      },
      spacing: { sm: '12px', md: '24px', lg: '56px', xl: '96px' },
      rounded: { sm: '2px', md: '6px', lg: '8px' },
      components: {
        'project-tile': { backgroundColor: '{colors.surface}', rounded: '{rounded.md}' },
        'button-primary': { backgroundColor: '{colors.primary}', textColor: '{colors.on-primary}', rounded: '{rounded.sm}' },
      },
    },
    rationale: {
      overview: 'Give work samples room to breathe and let captions carry the story.',
      colors: 'Mostly monochrome with one editorial accent for active states and tags.',
      typography: 'Pair expressive display type with neutral UI labels.',
      layout: 'Use magazine-like rhythm, alternating scale, and strong image or canvas placements.',
      elevation: 'Flat by default; depth comes from image scale and whitespace.',
      shapes: 'Keep framing quiet so the creative work stays primary.',
      components: 'Project tiles, filters, captions, and contact modules should feel curated rather than dashboard-like.',
      dos: ['Show concrete work above the fold.', 'Make project metadata scannable.'],
      donts: ['Do not copy a known magazine, gallery, studio, or portfolio trade dress.', 'Do not use stock-like abstract backgrounds as the main proof.', 'Do not overcrowd the page with badges.'],
      sections: {},
    },
    previewArtifactId: null,
    lintStatus: 'unknown',
    createdByUserId: null,
  },
  {
    schemaVersion: DESIGN_TEMPLATE_PACK_SCHEMA_VERSION,
    id: 'dtp_enterprise_clarity',
    source: 'official',
    format: 'dudesign-template-v1',
    visibility: 'public',
    status: 'published',
    name: 'Enterprise Clarity',
    description: 'A sober B2B system for complex products, procurement confidence, and repeated scanning.',
    version: '1.0.0',
    designTokens: {
      colors: {
        primary: '#253247',
        'on-primary': '#FFFFFF',
        background: '#F6F7F9',
        surface: '#FFFFFF',
        accent: '#2F6FED',
      },
      typography: {
        display: { fontFamily: 'Inter, ui-sans-serif, system-ui', fontSize: '44px', fontWeight: 680, lineHeight: 1.12 },
        body: { fontFamily: 'Inter, ui-sans-serif, system-ui', fontSize: '15px', fontWeight: 400, lineHeight: 1.62 },
      },
      spacing: { sm: '8px', md: '18px', lg: '36px', xl: '64px' },
      rounded: { sm: '4px', md: '8px', lg: '12px' },
      components: {
        'feature-row': { backgroundColor: '{colors.surface}', rounded: '{rounded.md}' },
        'button-primary': { backgroundColor: '{colors.primary}', textColor: '{colors.on-primary}', rounded: '{rounded.sm}' },
      },
    },
    rationale: {
      overview: 'Keep dense information orderly, with trust proof and implementation context close to claims.',
      colors: 'Neutral operational colors with blue reserved for navigation, links, and primary actions.',
      typography: 'Professional and compact. Favor subheads and labels that support scanning.',
      layout: 'Use clear bands, tables, diagrams, and side-by-side evidence blocks.',
      elevation: 'Low depth; use borders and banding for separation.',
      shapes: 'Conservative radius, no playful decorative forms.',
      components: 'Feature matrices, integration lists, role-based use cases, and security sections are first-class.',
      dos: ['Make deployment and security concerns visible.', 'Support comparison and repeated review.'],
      donts: ['Do not copy or imitate a specific enterprise software homepage or console trade dress.', 'Do not use oversized marketing-only hero composition for operational tools.', 'Do not obscure dense data inside decorative cards.'],
      sections: {},
    },
    previewArtifactId: null,
    lintStatus: 'unknown',
    createdByUserId: null,
  },
  {
    schemaVersion: DESIGN_TEMPLATE_PACK_SCHEMA_VERSION,
    id: 'dtp_mobility_launch',
    source: 'official',
    format: 'dudesign-template-v1',
    visibility: 'public',
    status: 'published',
    name: 'Mobility Launch',
    description: 'A motion-aware launch system for automotive, transportation, robotics, and hardware mobility.',
    version: '1.0.0',
    designTokens: {
      colors: {
        primary: '#101113',
        'on-primary': '#FFFFFF',
        background: '#F5F2EC',
        surface: '#FFFFFF',
        accent: '#B91C1C',
      },
      typography: {
        display: { fontFamily: 'Inter, ui-sans-serif, system-ui', fontSize: '54px', fontWeight: 720, lineHeight: 1.0 },
        body: { fontFamily: 'Inter, ui-sans-serif, system-ui', fontSize: '16px', fontWeight: 400, lineHeight: 1.55 },
      },
      spacing: { sm: '10px', md: '22px', lg: '48px', xl: '88px' },
      rounded: { sm: '4px', md: '10px', lg: '20px' },
      components: {
        'spec-strip': { backgroundColor: '{colors.primary}', textColor: '{colors.on-primary}', rounded: '{rounded.md}' },
        'button-primary': { backgroundColor: '{colors.accent}', textColor: '{colors.on-primary}', rounded: '{rounded.sm}' },
      },
    },
    rationale: {
      overview: 'Use strong silhouettes, specs, and motion cues while keeping the object inspectable.',
      colors: 'Charcoal and warm neutrals dominate; red accent adds urgency without becoming a brand clone.',
      typography: 'Confident technical headlines with compact spec labels.',
      layout: 'Lead with the vehicle or hardware object, then show specs, experience, safety, and availability.',
      elevation: 'Use layered panels only where specs need contrast.',
      shapes: 'Use subtle aerodynamic curves in layout, not decorative blobs.',
      components: 'Spec strips, model comparison, safety highlights, and configurator-like controls are key.',
      dos: ['Show product form, scale, and practical details.', 'Use motion cues to support understanding.'],
      donts: ['Do not imitate any automaker grille, badge, typography, launch page, or photography trade dress.', 'Do not hide safety information behind vibe-only visuals.'],
      sections: {},
    },
    previewArtifactId: null,
    lintStatus: 'unknown',
    createdByUserId: null,
  },
  {
    schemaVersion: DESIGN_TEMPLATE_PACK_SCHEMA_VERSION,
    id: 'dtp_developer_workflow',
    source: 'official',
    format: 'dudesign-template-v1',
    visibility: 'public',
    status: 'published',
    name: 'Developer Workflow',
    description: 'A precise developer-tool system for APIs, CLIs, infrastructure, and code-adjacent products.',
    version: '1.0.0',
    designTokens: {
      colors: {
        primary: '#0F172A',
        'on-primary': '#E5E7EB',
        background: '#F8FAFC',
        surface: '#FFFFFF',
        accent: '#14B8A6',
      },
      typography: {
        display: { fontFamily: 'Inter, ui-sans-serif, system-ui', fontSize: '46px', fontWeight: 700, lineHeight: 1.08 },
        mono: { fontFamily: 'JetBrains Mono, ui-monospace, monospace', fontSize: '13px', fontWeight: 500, lineHeight: 1.55 },
        body: { fontFamily: 'Inter, ui-sans-serif, system-ui', fontSize: '16px', fontWeight: 400, lineHeight: 1.6 },
      },
      spacing: { sm: '8px', md: '18px', lg: '40px', xl: '72px' },
      rounded: { sm: '4px', md: '8px', lg: '12px' },
      components: {
        'code-panel': { backgroundColor: '{colors.primary}', textColor: '{colors.on-primary}', rounded: '{rounded.md}' },
        'button-primary': { backgroundColor: '{colors.accent}', textColor: '{colors.primary}', rounded: '{rounded.sm}' },
      },
    },
    rationale: {
      overview: 'Make implementation feel obvious: code samples, workflow steps, and integration state should be first-class.',
      colors: 'Dark code panels contrast with light documentation surfaces; teal accent marks success or active state.',
      typography: 'Use a trustworthy sans for product copy and a readable mono only for real code or commands.',
      layout: 'Expose API examples, quickstart steps, and architecture diagrams without overwhelming the first viewport.',
      elevation: 'Prefer borders and terminal-like panels over heavy shadows.',
      shapes: 'Crisp edges and predictable controls.',
      components: 'Code panels, tabs, copy buttons, status badges, and changelog snippets are expected.',
      dos: ['Include plausible code or CLI examples.', 'Make docs and product value connect in the same flow.'],
      donts: ['Do not fake unreadable code texture.', 'Do not copy any specific developer platform landing page chrome.'],
      sections: {},
    },
    previewArtifactId: null,
    lintStatus: 'unknown',
    createdByUserId: null,
  },
  {
    schemaVersion: DESIGN_TEMPLATE_PACK_SCHEMA_VERSION,
    id: 'dtp_warm_commerce',
    source: 'official',
    format: 'dudesign-template-v1',
    visibility: 'public',
    status: 'published',
    name: 'Warm Commerce',
    description: 'A product-commerce system for curated goods, lifestyle offers, and approachable conversion.',
    version: '1.0.0',
    designTokens: {
      colors: {
        primary: '#312A25',
        'on-primary': '#FFFFFF',
        background: '#FAF6EF',
        surface: '#FFFFFF',
        accent: '#C96A43',
      },
      typography: {
        display: { fontFamily: 'Inter, ui-sans-serif, system-ui', fontSize: '50px', fontWeight: 660, lineHeight: 1.06 },
        body: { fontFamily: 'Inter, ui-sans-serif, system-ui', fontSize: '16px', fontWeight: 400, lineHeight: 1.64 },
      },
      spacing: { sm: '10px', md: '22px', lg: '44px', xl: '76px' },
      rounded: { sm: '6px', md: '12px', lg: '18px' },
      components: {
        'product-card': { backgroundColor: '{colors.surface}', rounded: '{rounded.md}' },
        'button-primary': { backgroundColor: '{colors.primary}', textColor: '{colors.on-primary}', rounded: '{rounded.sm}' },
      },
    },
    rationale: {
      overview: 'Balance warmth, product inspection, and purchasing clarity.',
      colors: 'Soft commerce neutrals with a single warm accent for price, promo, or availability.',
      typography: 'Friendly but not cute; support product detail scanning.',
      layout: 'Product grids, bundles, story bands, and trust proof should remain clean and transactional.',
      elevation: 'Subtle depth on product cards only.',
      shapes: 'Moderate radius for approachability.',
      components: 'Product cards, bundles, review snippets, variant selectors, and sticky buy actions are core.',
      dos: ['Make product details and purchase path visible.', 'Use real product imagery or generated product-like assets when needed.'],
      donts: ['Do not bury buying controls under editorial content.', 'Do not copy any marketplace or fashion brand trade dress.'],
      sections: {},
    },
    previewArtifactId: null,
    lintStatus: 'unknown',
    createdByUserId: null,
  },
  {
    schemaVersion: DESIGN_TEMPLATE_PACK_SCHEMA_VERSION,
    id: 'dtp_data_operations',
    source: 'official',
    format: 'dudesign-template-v1',
    visibility: 'public',
    status: 'published',
    name: 'Data-Dense Operations',
    description: 'A compact operational system for dashboards, admin tools, monitoring, and repeated workflows.',
    version: '1.0.0',
    designTokens: {
      colors: {
        primary: '#1F2937',
        'on-primary': '#FFFFFF',
        background: '#F3F4F6',
        surface: '#FFFFFF',
        accent: '#2563EB',
        success: '#047857',
        danger: '#B91C1C',
      },
      typography: {
        display: { fontFamily: 'Inter, ui-sans-serif, system-ui', fontSize: '34px', fontWeight: 700, lineHeight: 1.14 },
        body: { fontFamily: 'Inter, ui-sans-serif, system-ui', fontSize: '14px', fontWeight: 400, lineHeight: 1.55 },
        label: { fontFamily: 'Inter, ui-sans-serif, system-ui', fontSize: '12px', fontWeight: 650, lineHeight: 1.25 },
      },
      spacing: { xs: '4px', sm: '8px', md: '16px', lg: '28px', xl: '48px' },
      rounded: { sm: '4px', md: '8px', lg: '10px' },
      components: {
        'data-table': { backgroundColor: '{colors.surface}', rounded: '{rounded.md}' },
        'button-primary': { backgroundColor: '{colors.accent}', textColor: '{colors.on-primary}', rounded: '{rounded.sm}' },
      },
    },
    rationale: {
      overview: 'Prioritize scanning, comparison, filters, error states, and fast repeated action.',
      colors: 'Neutral operational surfaces with semantic status colors.',
      typography: 'Dense, legible, and label-driven.',
      layout: 'Navigation, filters, tables, charts, and detail drawers should be predictable and stable.',
      elevation: 'Use borders and layout bands before shadows.',
      shapes: 'Small radii preserve density.',
      components: 'Tables, filters, tabs, segmented controls, drawers, and metric strips are primary.',
      dos: ['Keep workflows dense but organized.', 'Show empty, loading, and error states.'],
      donts: ['Do not copy or imitate a specific analytics, monitoring, or admin platform trade dress.', 'Do not make a marketing landing page for an operational tool.', 'Do not use oversized cards where tables or lists are more useful.'],
      sections: {},
    },
    previewArtifactId: null,
    lintStatus: 'unknown',
    createdByUserId: null,
  },
  {
    schemaVersion: DESIGN_TEMPLATE_PACK_SCHEMA_VERSION,
    id: 'dtp_dynamic_encyclopedia_card',
    templateRole: 'parent_pack',
    supportedProductModes: ['dynamic_encyclopedia_card'],
    supportedEntryCategories: ['encyclopedia'],
    source: 'official',
    format: 'dudesign-template-v1',
    visibility: 'public',
    status: 'published',
    name: 'Dynamic Encyclopedia Entry Card',
    description: 'An interactive encyclopedia-style card package for compact knowledge entries, entity facts, and mobile iframe embedding.',
    version: '1.0.0',
    designTokens: {
      colors: {
        primary: '#6487FA',
        'on-primary': '#FFFFFF',
        background: '#F8F8F8',
        surface: '#FFFFFF',
        text: '#1E1F24',
        muted: '#848691',
        subtle: '#B7B9C1',
      },
      typography: {
        display: { fontFamily: 'Inter, PingFang SC, system-ui, sans-serif', fontSize: '24px', fontWeight: 700, lineHeight: 1.18 },
        body: { fontFamily: 'Inter, PingFang SC, system-ui, sans-serif', fontSize: '14px', fontWeight: 400, lineHeight: 1.58 },
        label: { fontFamily: 'Inter, PingFang SC, system-ui, sans-serif', fontSize: '12px', fontWeight: 600, lineHeight: 1.35 },
      },
      spacing: { xs: '4px', sm: '8px', md: '14px', lg: '20px', xl: '28px' },
      rounded: { sm: '6px', md: '10px', lg: '14px' },
      components: {
        'pc-card-frame': { width: 788, height: 492, backgroundColor: '{colors.surface}', rounded: '{rounded.lg}' },
        'wise-standard-frame': { width: 380, height: 456, ratio: '1:1.2', backgroundColor: '{colors.surface}', rounded: '{rounded.lg}' },
        'wise-large-frame': { width: 396, height: 475, ratio: '1:1.2' },
        'wise-small-frame': { width: 300, height: 360, ratio: '1:1.2' },
        'button-primary': { backgroundColor: '{colors.primary}', textColor: '{colors.on-primary}', rounded: '{rounded.md}' },
        'scroll-container': { overflowY: 'auto', webkitOverflowScrolling: 'touch', bodyScroll: false },
      },
    },
    rationale: {
      overview: 'Use this as a template package for dynamic encyclopedia entry cards. It should produce compact, inspectable entity knowledge with clear facts, tabs or chips, and safe iframe/mobile touch behavior.',
      colors: 'Primary action color is #6487FA. Content surfaces are #FFFFFF and #F8F8F8. Main text is #1E1F24, secondary text is #848691, and tertiary text is #B7B9C1.',
      typography: 'Chinese and mixed-language encyclopedia content must stay legible at 300px width. Prefer short labels, dense facts, and restrained hierarchy.',
      layout: 'PC must render perfectly at 788x492. Mobile standard is 380x456. Also tolerate 396x475 and 300x360 with only minor imperfections. Preserve width:height ratio near 1:1.2 on mobile.',
      elevation: 'Use subtle borders or shallow shadows only where needed to separate facts, media, and interactive controls.',
      shapes: 'Use moderate radii. Avoid decorative blobs or brand-like chrome that competes with encyclopedia content.',
      components: 'Expected subtemplates include entity summary card, fact timeline, media-light gallery, relation graph preview, Q&A fact list, and expandable detail sections. Keep all long content in explicit overflow containers.',
      dos: [
        'Wrap the page in a dedicated scroll container; do not rely on body scrolling.',
        'Use visible scroll affordances when content overflows.',
        'Keep iframe-embedded mobile pages compatible with native page gestures.',
        'Use local interactive UI states instead of external navigation.',
      ],
      donts: [
        'Do not copy or imitate any public encyclopedia, search engine, browser, or mobile app trade dress.',
        'Do not attach global touchmove preventDefault handlers to document, body, or html.',
        'Do not set touch-action: none globally; only use local touch behavior on precise controls.',
        'Do not call stopPropagation for touchstart, touchmove, or touchend on scroll gestures.',
        'Do not rely on video, download actions, or outbound links as core interactions.',
      ],
      sections: {
        sizing: 'PC: 788x492 exact composition. WISE standard: 380x456. WISE compatibility: 396x475 and 300x360. Mobile ratio should remain width:height = 1:1.2.',
        scrolling: 'Set html/body to height:100% and overflow:hidden when generating standalone pages. Put all content inside .scroll-container with overflow-y:auto and -webkit-overflow-scrolling:touch.',
        iframeTouch: 'Avoid iframe pinch/zoom conflicts. Do not globally intercept touchmove. If prevention is required, only block non-scroll areas and always allow .scroll-container and iframe targets.',
        canvasTouch: 'Canvas-like interactions must use touch-action: pan-x pan-y and should leave physical spacing from iframe or scroll areas.',
        compatibility: 'Android compatibility is prioritized: avoid video resources, downloads, and jump links unless explicitly requested.',
        packageChildren: 'This root template represents a package. Child templates: dtp_dynamic_encyclopedia_summary_card (summary-card: entity summary and key facts), dtp_dynamic_encyclopedia_timeline_card (timeline-card: events or development history), dtp_dynamic_encyclopedia_relation_card (relation-card: related entities and lightweight graph preview), dtp_dynamic_encyclopedia_compare_card (comparison-card: side-by-side fact comparison), dtp_dynamic_encyclopedia_expandable_card (expandable-fact-card: progressive disclosure for long encyclopedic details). All child templates inherit sizing, color, iframe/touch, scroll, and delivery safety constraints.',
      },
    },
    previewArtifactId: null,
    lintStatus: 'unknown',
    createdByUserId: null,
  },
  {
    schemaVersion: DESIGN_TEMPLATE_PACK_SCHEMA_VERSION,
    id: 'dtp_dynamic_encyclopedia_summary_card',
    parentPackId: 'dtp_dynamic_encyclopedia_card',
    templateRole: 'child_template',
    supportedProductModes: ['dynamic_encyclopedia_card'],
    supportedEntryCategories: ['名人', '机构组织', '企业', '学校', '物品产品', '知识术语'],
    source: 'official',
    format: 'dudesign-template-v1',
    visibility: 'public',
    status: 'published',
    name: 'Dynamic Encyclopedia Summary Card',
    description: 'A child template for core entity facts, short summaries, and key metrics inside the dynamic encyclopedia card package.',
    version: '1.0.0',
    designTokens: {
      colors: {
        primary: '#6487FA',
        'on-primary': '#FFFFFF',
        background: '#F8F8F8',
        surface: '#FFFFFF',
        text: '#1E1F24',
        muted: '#848691',
        subtle: '#B7B9C1',
      },
      typography: {
        display: { fontFamily: 'Inter, PingFang SC, system-ui, sans-serif', fontSize: '24px', fontWeight: 700, lineHeight: 1.18 },
        body: { fontFamily: 'Inter, PingFang SC, system-ui, sans-serif', fontSize: '14px', fontWeight: 400, lineHeight: 1.58 },
        label: { fontFamily: 'Inter, PingFang SC, system-ui, sans-serif', fontSize: '12px', fontWeight: 600, lineHeight: 1.35 },
      },
      spacing: { xs: '4px', sm: '8px', md: '14px', lg: '20px', xl: '28px' },
      rounded: { sm: '6px', md: '10px', lg: '14px' },
      components: {
        'pc-card-frame': { width: 788, height: 492, backgroundColor: '{colors.surface}', rounded: '{rounded.lg}' },
        'wise-standard-frame': { width: 380, height: 456, ratio: '1:1.2', backgroundColor: '{colors.surface}', rounded: '{rounded.lg}' },
        'fact-grid': { minColumns: 2, maxColumns: 4, backgroundColor: '{colors.surface}', rounded: '{rounded.md}' },
        'scroll-container': { overflowY: 'auto', webkitOverflowScrolling: 'touch', bodyScroll: false },
        'button-primary': { backgroundColor: '{colors.primary}', textColor: '{colors.on-primary}', rounded: '{rounded.md}' },
      },
    },
    rationale: {
      overview: 'Use this child template when the entry is best represented by a compact identity summary and verified key facts.',
      colors: 'Inherit #6487FA primary actions and neutral encyclopedia surfaces from the parent package.',
      typography: 'Prioritize short labels, dense facts, and legible CJK content at 300px width.',
      layout: 'Lead with entry name, one-sentence neutral summary, then grouped facts and optional chips. Preserve PC 788x492 and mobile 380x456 constraints.',
      elevation: 'Use borders and shallow separation only where fact groups need hierarchy.',
      shapes: 'Moderate radii inherited from the parent package.',
      components: 'Summary header, fact grid, source hint, tabs/chips for compact fact groups, explicit scroll container.',
      dos: [
        'Keep claims factual and compact.',
        'Use grouped facts rather than long prose when space is limited.',
        'Place overflow content in .scroll-container.',
      ],
      donts: [
        'Do not copy or imitate any public encyclopedia, search engine, browser, or mobile app trade dress.',
        'Do not invent missing entity facts.',
        'Do not rely on body scrolling.',
      ],
      sections: {
        parentPack: 'Inherits sizing, iframe/touch, scroll, and color constraints from dtp_dynamic_encyclopedia_card.',
        dataShape: 'Best with entry title, concise description, category, aliases, dates, locations, metrics, tags, and source notes.',
      },
    },
    previewArtifactId: null,
    lintStatus: 'unknown',
    createdByUserId: null,
  },
  {
    schemaVersion: DESIGN_TEMPLATE_PACK_SCHEMA_VERSION,
    id: 'dtp_dynamic_encyclopedia_timeline_card',
    parentPackId: 'dtp_dynamic_encyclopedia_card',
    templateRole: 'child_template',
    supportedProductModes: ['dynamic_encyclopedia_card'],
    supportedEntryCategories: ['历史人物', '影视作品', '文学著作', '企业', '文化活动', '游戏'],
    source: 'official',
    format: 'dudesign-template-v1',
    visibility: 'public',
    status: 'published',
    name: 'Dynamic Encyclopedia Timeline Card',
    description: 'A child template for biographies, histories, releases, and staged entity development.',
    version: '1.0.0',
    designTokens: {
      colors: {
        primary: '#6487FA',
        'on-primary': '#FFFFFF',
        background: '#F8F8F8',
        surface: '#FFFFFF',
        text: '#1E1F24',
        muted: '#848691',
        subtle: '#B7B9C1',
      },
      typography: {
        display: { fontFamily: 'Inter, PingFang SC, system-ui, sans-serif', fontSize: '24px', fontWeight: 700, lineHeight: 1.18 },
        body: { fontFamily: 'Inter, PingFang SC, system-ui, sans-serif', fontSize: '14px', fontWeight: 400, lineHeight: 1.58 },
        label: { fontFamily: 'Inter, PingFang SC, system-ui, sans-serif', fontSize: '12px', fontWeight: 600, lineHeight: 1.35 },
      },
      spacing: { xs: '4px', sm: '8px', md: '14px', lg: '20px', xl: '28px' },
      rounded: { sm: '6px', md: '10px', lg: '14px' },
      components: {
        'pc-card-frame': { width: 788, height: 492, backgroundColor: '{colors.surface}', rounded: '{rounded.lg}' },
        'wise-standard-frame': { width: 380, height: 456, ratio: '1:1.2', backgroundColor: '{colors.surface}', rounded: '{rounded.lg}' },
        'timeline-track': { accentColor: '{colors.primary}', markerSize: 8 },
        'scroll-container': { overflowY: 'auto', webkitOverflowScrolling: 'touch', bodyScroll: false },
        'button-primary': { backgroundColor: '{colors.primary}', textColor: '{colors.on-primary}', rounded: '{rounded.md}' },
      },
    },
    rationale: {
      overview: 'Use this child template when the entry has a meaningful sequence of events, milestones, releases, or life stages.',
      colors: 'Use the parent palette; timeline markers may use #6487FA sparingly.',
      typography: 'Dates and event labels must remain readable in compact mobile frames.',
      layout: 'Lead with entry summary, then a vertical or segmented timeline inside a scroll container. Preserve PC and WISE frame constraints.',
      elevation: 'Use light separation for event cards only.',
      shapes: 'Moderate radii; markers should be small and precise.',
      components: 'Timeline track, milestone cards, period filters, summary chips, explicit overflow container.',
      dos: [
        'Keep every event tied to supplied entry context.',
        'Group sparse dates into phases when exact dates are unavailable.',
        'Make overflow visually discoverable.',
      ],
      donts: [
        'Do not copy or imitate any public encyclopedia, search engine, browser, or mobile app trade dress.',
        'Do not fabricate dates or milestones.',
        'Do not turn timeline controls into outbound navigation.',
        'Do not globally intercept touch gestures.',
      ],
      sections: {
        parentPack: 'Inherits sizing, iframe/touch, scroll, and color constraints from dtp_dynamic_encyclopedia_card.',
        dataShape: 'Best with dated events, life stages, development history, releases, or notable milestones.',
      },
    },
    previewArtifactId: null,
    lintStatus: 'unknown',
    createdByUserId: null,
  },
  {
    schemaVersion: DESIGN_TEMPLATE_PACK_SCHEMA_VERSION,
    id: 'dtp_dynamic_encyclopedia_relation_card',
    parentPackId: 'dtp_dynamic_encyclopedia_card',
    templateRole: 'child_template',
    supportedProductModes: ['dynamic_encyclopedia_card'],
    supportedEntryCategories: ['名人', '历史人物', '企业', '机构组织', '影视作品', '文学著作', '游戏'],
    source: 'official',
    format: 'dudesign-template-v1',
    visibility: 'public',
    status: 'published',
    name: 'Dynamic Encyclopedia Relation Card',
    description: 'A child template for related entities, lightweight relationship maps, and local knowledge navigation.',
    version: '1.0.0',
    designTokens: {
      colors: {
        primary: '#6487FA',
        'on-primary': '#FFFFFF',
        background: '#F8F8F8',
        surface: '#FFFFFF',
        text: '#1E1F24',
        muted: '#848691',
        subtle: '#B7B9C1',
      },
      typography: {
        display: { fontFamily: 'Inter, PingFang SC, system-ui, sans-serif', fontSize: '24px', fontWeight: 700, lineHeight: 1.18 },
        body: { fontFamily: 'Inter, PingFang SC, system-ui, sans-serif', fontSize: '14px', fontWeight: 400, lineHeight: 1.58 },
        label: { fontFamily: 'Inter, PingFang SC, system-ui, sans-serif', fontSize: '12px', fontWeight: 600, lineHeight: 1.35 },
      },
      spacing: { xs: '4px', sm: '8px', md: '14px', lg: '20px', xl: '28px' },
      rounded: { sm: '6px', md: '10px', lg: '14px' },
      components: {
        'pc-card-frame': { width: 788, height: 492, backgroundColor: '{colors.surface}', rounded: '{rounded.lg}' },
        'wise-standard-frame': { width: 380, height: 456, ratio: '1:1.2', backgroundColor: '{colors.surface}', rounded: '{rounded.lg}' },
        'relation-node': { maxNodes: 8, accentColor: '{colors.primary}', rounded: '{rounded.md}' },
        'relation-edge': { strokeColor: '{colors.subtle}', strokeWidth: 1 },
        'scroll-container': { overflowY: 'auto', webkitOverflowScrolling: 'touch', bodyScroll: false },
        'button-primary': { backgroundColor: '{colors.primary}', textColor: '{colors.on-primary}', rounded: '{rounded.md}' },
      },
    },
    rationale: {
      overview: 'Use this child template when the entry is best understood through people, works, organizations, roles, or related concepts around the entity.',
      colors: 'Inherit the parent encyclopedia palette. Use #6487FA only for the current entry and selected relation state.',
      typography: 'Relation labels must stay compact and legible in mobile frames; avoid tiny graph text.',
      layout: 'Lead with the current entity, then show a bounded local relation map plus a scrollable relation list. Preserve PC 788x492 and mobile 380x456 constraints.',
      elevation: 'Use subtle borders for relation groups, not heavy graph containers.',
      shapes: 'Moderate radii inherited from the parent package; graph nodes should be simple chips or circles.',
      components: 'Entity anchor, relation nodes, relation list, local filter chips, explicit scroll container.',
      dos: [
        'Limit relation maps to a small readable set.',
        'Use local state for relation focus instead of outbound links.',
        'Place overflow relation details in .scroll-container.',
      ],
      donts: [
        'Do not copy or imitate any public encyclopedia, search engine, browser, or mobile app trade dress.',
        'Do not fabricate relationships that are not present in the supplied context.',
        'Do not rely on canvas-only interactions that block mobile scroll gestures.',
      ],
      sections: {
        parentPack: 'Inherits sizing, iframe/touch, scroll, and color constraints from dtp_dynamic_encyclopedia_card.',
        dataShape: 'Best with related people, works, organizations, roles, aliases, source/target pairs, or entity relation notes.',
      },
    },
    previewArtifactId: null,
    lintStatus: 'unknown',
    createdByUserId: null,
  },
  {
    schemaVersion: DESIGN_TEMPLATE_PACK_SCHEMA_VERSION,
    id: 'dtp_dynamic_encyclopedia_compare_card',
    parentPackId: 'dtp_dynamic_encyclopedia_card',
    templateRole: 'child_template',
    supportedProductModes: ['dynamic_encyclopedia_card'],
    supportedEntryCategories: ['知识术语', '物品产品', '产品设备', '企业', '学校', '游戏'],
    source: 'official',
    format: 'dudesign-template-v1',
    visibility: 'public',
    status: 'published',
    name: 'Dynamic Encyclopedia Compare Card',
    description: 'A child template for side-by-side fact comparison, concept disambiguation, and compact decision support.',
    version: '1.0.0',
    designTokens: {
      colors: {
        primary: '#6487FA',
        'on-primary': '#FFFFFF',
        background: '#F8F8F8',
        surface: '#FFFFFF',
        text: '#1E1F24',
        muted: '#848691',
        subtle: '#B7B9C1',
      },
      typography: {
        display: { fontFamily: 'Inter, PingFang SC, system-ui, sans-serif', fontSize: '24px', fontWeight: 700, lineHeight: 1.18 },
        body: { fontFamily: 'Inter, PingFang SC, system-ui, sans-serif', fontSize: '14px', fontWeight: 400, lineHeight: 1.58 },
        label: { fontFamily: 'Inter, PingFang SC, system-ui, sans-serif', fontSize: '12px', fontWeight: 600, lineHeight: 1.35 },
      },
      spacing: { xs: '4px', sm: '8px', md: '14px', lg: '20px', xl: '28px' },
      rounded: { sm: '6px', md: '10px', lg: '14px' },
      components: {
        'pc-card-frame': { width: 788, height: 492, backgroundColor: '{colors.surface}', rounded: '{rounded.lg}' },
        'wise-standard-frame': { width: 380, height: 456, ratio: '1:1.2', backgroundColor: '{colors.surface}', rounded: '{rounded.lg}' },
        'comparison-table': { maxColumns: 3, stickyFirstColumn: false, backgroundColor: '{colors.surface}' },
        'comparison-row': { minHeight: 36, borderColor: '{colors.subtle}' },
        'scroll-container': { overflowY: 'auto', webkitOverflowScrolling: 'touch', bodyScroll: false },
        'button-primary': { backgroundColor: '{colors.primary}', textColor: '{colors.on-primary}', rounded: '{rounded.md}' },
      },
    },
    rationale: {
      overview: 'Use this child template when users need to distinguish similar concepts, products, organizations, editions, or factual dimensions.',
      colors: 'Inherit the parent palette; use the accent only to highlight differences or current selection.',
      typography: 'Row labels and comparison values must remain readable at 300px width; prefer short neutral copy.',
      layout: 'Lead with the comparison question, then show a bounded side-by-side table or segmented comparison. Preserve PC and WISE frame constraints.',
      elevation: 'Use row dividers and subtle grouping instead of card stacks inside cards.',
      shapes: 'Moderate radii inherited from the parent package.',
      components: 'Comparison header, side-by-side rows, difference chips, source hints, explicit scroll container.',
      dos: [
        'Compare only facts supplied by entry context.',
        'Use concise labels and avoid marketing claims.',
        'Allow horizontal density on PC while preserving vertical scroll on mobile.',
      ],
      donts: [
        'Do not copy or imitate any public encyclopedia, search engine, browser, or mobile app trade dress.',
        'Do not invent competitors, editions, specs, or pros/cons.',
        'Do not use oversized cards where a table is clearer.',
      ],
      sections: {
        parentPack: 'Inherits sizing, iframe/touch, scroll, and color constraints from dtp_dynamic_encyclopedia_card.',
        dataShape: 'Best with comparable entities, editions, concepts, definitions, specs, dimensions, or disambiguation notes.',
      },
    },
    previewArtifactId: null,
    lintStatus: 'unknown',
    createdByUserId: null,
  },
  {
    schemaVersion: DESIGN_TEMPLATE_PACK_SCHEMA_VERSION,
    id: 'dtp_dynamic_encyclopedia_expandable_card',
    parentPackId: 'dtp_dynamic_encyclopedia_card',
    templateRole: 'child_template',
    supportedProductModes: ['dynamic_encyclopedia_card'],
    supportedEntryCategories: ['知识术语', '历史人物', '影视作品', '文学著作', '文化活动', '机构组织'],
    source: 'official',
    format: 'dudesign-template-v1',
    visibility: 'public',
    status: 'published',
    name: 'Dynamic Encyclopedia Expandable Fact Card',
    description: 'A child template for progressive disclosure, long fact sections, and locally expandable encyclopedia details.',
    version: '1.0.0',
    designTokens: {
      colors: {
        primary: '#6487FA',
        'on-primary': '#FFFFFF',
        background: '#F8F8F8',
        surface: '#FFFFFF',
        text: '#1E1F24',
        muted: '#848691',
        subtle: '#B7B9C1',
      },
      typography: {
        display: { fontFamily: 'Inter, PingFang SC, system-ui, sans-serif', fontSize: '24px', fontWeight: 700, lineHeight: 1.18 },
        body: { fontFamily: 'Inter, PingFang SC, system-ui, sans-serif', fontSize: '14px', fontWeight: 400, lineHeight: 1.58 },
        label: { fontFamily: 'Inter, PingFang SC, system-ui, sans-serif', fontSize: '12px', fontWeight: 600, lineHeight: 1.35 },
      },
      spacing: { xs: '4px', sm: '8px', md: '14px', lg: '20px', xl: '28px' },
      rounded: { sm: '6px', md: '10px', lg: '14px' },
      components: {
        'pc-card-frame': { width: 788, height: 492, backgroundColor: '{colors.surface}', rounded: '{rounded.lg}' },
        'wise-standard-frame': { width: 380, height: 456, ratio: '1:1.2', backgroundColor: '{colors.surface}', rounded: '{rounded.lg}' },
        'accordion-section': { minHeight: 40, rounded: '{rounded.md}', borderColor: '{colors.subtle}' },
        'fact-callout': { backgroundColor: '#EEF3FF', textColor: '{colors.text}', rounded: '{rounded.md}' },
        'scroll-container': { overflowY: 'auto', webkitOverflowScrolling: 'touch', bodyScroll: false },
        'button-primary': { backgroundColor: '{colors.primary}', textColor: '{colors.on-primary}', rounded: '{rounded.md}' },
      },
    },
    rationale: {
      overview: 'Use this child template when the entry contains longer definitions, sections, caveats, or layered explanations that should be progressively revealed.',
      colors: 'Inherit the parent palette. Use light blue callouts only for key facts or current expanded sections.',
      typography: 'Accordion labels must be concise; expanded text should stay readable and avoid wall-of-text density.',
      layout: 'Lead with a compact summary and expose details through local expandable sections inside the scroll container.',
      elevation: 'Use shallow separation between expandable sections.',
      shapes: 'Moderate radii inherited from the parent package.',
      components: 'Summary header, accordion sections, fact callouts, source hint, explicit scroll container.',
      dos: [
        'Use progressive disclosure for long facts.',
        'Keep expanded content inside local scroll and accordion states.',
        'Make current expanded state obvious without external navigation.',
      ],
      donts: [
        'Do not copy or imitate any public encyclopedia, search engine, browser, or mobile app trade dress.',
        'Do not hide essential facts behind too many nested controls.',
        'Do not rely on body scrolling or global touch interception.',
      ],
      sections: {
        parentPack: 'Inherits sizing, iframe/touch, scroll, and color constraints from dtp_dynamic_encyclopedia_card.',
        dataShape: 'Best with long definitions, layered explanations, sections, caveats, frequently asked facts, or source notes.',
      },
    },
    previewArtifactId: null,
    lintStatus: 'unknown',
    createdByUserId: null,
  },
]
